version: '3.3'

services:

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    image: web-app
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: web-app-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example






