spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    table: schema_version
  thymeleaf:
    mode: HTML

logging:
  file:
    name: ./log/spring-cdos.log
  level:
    web: DEBUG
    com.marmaris: DEBUG
    org:
      hibernate:
        SQL: INFO # DEBUG for SQL queries
        type: INFO # TRACE for SQL parameters
        stat: DEBUG